name = "AcceleratorSimUtils"
uuid = "8b14b3b2-39c5-4be4-bdc0-0b322e577224"
authors = ["mattsignorelli <mgs255@cornell.edu> and contributors"]
version = "0.4.1"

[deps]
AtomicAndPhysicalConstants = "5c0d271c-5419-4163-b387-496237733d8b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AtomicAndPhysicalConstants = "0.6"
FFTW = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
